package com.caregiver.controller;

import com.caregiver.model.Booking;
import com.caregiver.repository.BookingRepository;
import com.caregiver.repository.ProfileRepository;
import com.caregiver.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = "*")
@Transactional(readOnly = true)
public class BookingController {

    @Autowired
    private BookingRepository bookingRepository;

    @Autowired
    private com.caregiver.repository.UserRepository userRepository;

    @Autowired
    private com.caregiver.repository.ProfileRepository profileRepository;

    // 1. Create Booking
    @Transactional
    @PostMapping("/book")
    public Booking createBooking(@RequestBody Map<String, Object> payload) {
        Booking booking = new Booking();
        // ID generated by DB

        booking.setClientId(Long.parseLong(payload.get("clientId").toString()));
        booking.setCaregiverId(Long.parseLong(payload.get("caregiverId").toString()));
        booking.setStatus("pending");

        String dateStr = (String) payload.get("serviceDate");
        if(dateStr.endsWith("Z")) {
            booking.setServiceDate(LocalDateTime.parse(dateStr, DateTimeFormatter.ISO_DATE_TIME));
        } else {
            booking.setServiceDate(LocalDateTime.parse(dateStr));
        }

        booking.setCreatedAt(LocalDateTime.now());

        return bookingRepository.save(booking);
    }

    // 2. Get Pending Bookings for Caregiver
    @GetMapping("/bookings/caregiver/{caregiverId}/pending")
    public List<Booking> getPendingBookings(@PathVariable Long caregiverId) {
        return StreamSupport.stream(bookingRepository.findByCaregiverId(caregiverId).spliterator(), false)
                .filter(b -> "pending".equalsIgnoreCase(b.getStatus()))
                .collect(Collectors.toList());
    }

    // 3. Accept Booking
    @Transactional
    @PostMapping("/bookings/{bookingId}/accept")
    public Booking acceptBooking(@PathVariable Long bookingId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        // Workflow: Pending -> Caregiver Accepted -> Admin Pending
        booking.setStatus("CAREGIVER_ACCEPTED");
        return bookingRepository.save(booking);
    }

    // 4. Reject Booking
    @Transactional
    @PostMapping("/bookings/{bookingId}/reject")
    public Booking rejectBooking(@PathVariable Long bookingId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        booking.setStatus("rejected");
        return bookingRepository.save(booking);
    }

    // 5. Get All History for Caregiver (Assigned + Completed)
    @GetMapping("/bookings/caregiver/{caregiverId}/history")
    public List<com.caregiver.model.BookingResponseDTO> getBookingHistory(@PathVariable Long caregiverId) {
        System.out.println("Fetching history for caregiver: " + caregiverId);
        return StreamSupport.stream(bookingRepository.findByCaregiverId(caregiverId).spliterator(), false)
                .filter(b -> {
                    String s = b.getStatus() == null ? "" : b.getStatus().toUpperCase();
                    return s.equals("APPROVED_BY_ADMIN") || s.contains("ASSIGNED") || s.contains("APPROVED") || s.equals("COMPLETED");
                })
                .sorted((b1, b2) -> b2.getServiceDate().compareTo(b1.getServiceDate())) // Latest first
                .map(this::convertToCaregiverViewDTO)
                .collect(Collectors.toList());
    }

    // 9. Mark Booking as Completed
    @Transactional
    @PostMapping("/bookings/{bookingId}/complete")
    public Booking completeBooking(@PathVariable Long bookingId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        booking.setStatus("COMPLETED");
        return bookingRepository.save(booking);
    }

    // --- NEW ENDPOINTS FOR CLIENT PORTAL ---

    // 6. Get Active Bookings for Client (Future + Approved)
    @GetMapping("/bookings/active/{clientId}")
    public List<com.caregiver.model.BookingResponseDTO> getActiveBookingsForClient(@PathVariable Long clientId) {
        List<Booking> bookings = bookingRepository.findByClientId(clientId);
        LocalDateTime now = LocalDateTime.now();

        return bookings.stream()
                .filter(b -> "APPROVED_BY_ADMIN".equalsIgnoreCase(b.getStatus()))
                .filter(b -> b.getServiceDate().isAfter(now.minusDays(1))) 
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }

    // 7. Get Request History for Client (All status)
    @GetMapping("/bookings/history/{clientId}")
    public List<com.caregiver.model.BookingResponseDTO> getClientBookingHistory(@PathVariable Long clientId) {
        List<Booking> bookings = bookingRepository.findByClientId(clientId);
        return bookings.stream()
                .sorted((b1, b2) -> b2.getServiceDate().compareTo(b1.getServiceDate())) 
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }

    // 8. Get Accepted Bookings for Caregiver (with Client Details)
    @GetMapping("/bookings/caregiver/{caregiverId}/accepted")
    public List<com.caregiver.model.BookingResponseDTO> getAcceptedBookings(@PathVariable Long caregiverId) {
        List<Booking> bookings = bookingRepository.findByCaregiverId(caregiverId);
        return bookings.stream()
                .filter(b -> "ACCEPTED".equalsIgnoreCase(b.getStatus()) || "CAREGIVER_ACCEPTED".equalsIgnoreCase(b.getStatus()) || "APPROVED_BY_ADMIN".equalsIgnoreCase(b.getStatus()))
                .map(this::convertToCaregiverViewDTO)
                .collect(Collectors.toList());
    }

    private com.caregiver.model.BookingResponseDTO convertToCaregiverViewDTO(Booking booking) {
        com.caregiver.model.User client = userRepository.findById(booking.getClientId()).orElse(null);
        com.caregiver.model.Profile clientProfile = profileRepository.findByUserId(booking.getClientId()).orElse(null);
        
        String clientName = "Unknown";
        String clientPhone = "N/A";
        String clientAddress = "N/A";

        if (client != null) {
            clientPhone = client.getPhone();
        }
        if (clientProfile != null) {
            clientName = clientProfile.getFirstName() + " " + clientProfile.getLastName();
            clientAddress = clientProfile.getPresentAddress();
        }

        return new com.caregiver.model.BookingResponseDTO(
            booking.getBookingId(),
            booking.getCaregiverId(),
            "Me", // Caregiver name is irrelevant here
            booking.getStatus(),
            booking.getServiceDate(),
            clientName,
            clientPhone,
            clientAddress
        );
    }

    private com.caregiver.model.BookingResponseDTO convertToDTO(Booking booking) {
        com.caregiver.model.Profile caregiver = profileRepository.findByUserId(booking.getCaregiverId()).orElse(null);
        String name = "Unknown";
        String profession = "N/A";
        String address = "N/A";

        if (caregiver != null) {
            name = caregiver.getFirstName() + " " + caregiver.getLastName();
            profession = caregiver.getProfession();
            address = caregiver.getPresentAddress();
        }

        return new com.caregiver.model.BookingResponseDTO(
                booking.getBookingId(),
                booking.getCaregiverId(),
                name,
                profession,
                booking.getStatus(),
                booking.getServiceDate(),
                address
        );
    }
}