package com.caregiver.controller;

import com.caregiver.model.Review;
import com.caregiver.repository.ReviewRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = "*")
public class ReviewController {

    @Autowired
    private ReviewRepository reviewRepository;

    @Autowired
    private com.caregiver.repository.ProfileRepository profileRepository;

    @PostMapping("/reviews")
    public Review createReview(@RequestBody Map<String, Object> payload) {
        Review review = new Review();
        // ID generated by DB
        review.setClientId(Long.parseLong(payload.get("clientId").toString()));
        review.setCaregiverId(Long.parseLong(payload.get("caregiverId").toString()));
        review.setRating(Integer.parseInt(payload.get("rating").toString()));
        review.setComment((String) payload.get("comment"));
        review.setStatus("published");
        review.setCreatedAt(LocalDateTime.now());
        
        return reviewRepository.save(review);
    }

    @GetMapping("/caregivers/{caregiverId}/reviews")
    public List<com.caregiver.model.ReviewResponseDTO> getCaregiverReviews(@PathVariable Long caregiverId) {
        List<Review> reviews = reviewRepository.findByCaregiverId(caregiverId);
        return reviews.stream().map(r -> {
            String reviewerName = "Anonymous";
            com.caregiver.model.Profile p = profileRepository.findByUserId(r.getClientId()).orElse(null);
            if(p != null) reviewerName = p.getFirstName() + " " + p.getLastName();
            
            return new com.caregiver.model.ReviewResponseDTO(
                r.getReviewId(),
                reviewerName,
                r.getRating(),
                r.getComment(),
                r.getCreatedAt()
            );
        }).collect(java.util.stream.Collectors.toList());
    }
}
