package com.caregiver.controller;

import com.caregiver.model.Schedule;
import com.caregiver.repository.ScheduleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/schedule")
@CrossOrigin(origins = "*")
public class ScheduleController {

    @Autowired
    private ScheduleRepository scheduleRepository;

    @PostMapping("/add")
    public Schedule addSchedule(@RequestBody Map<String, Object> payload) {
        Schedule schedule = new Schedule();
        // ID generated by DB
        schedule.setCaregiverId(Long.parseLong(payload.get("caregiverId").toString()));
        schedule.setDayOfWeek(payload.get("dayOfWeek").toString());
        schedule.setStartTime(payload.get("startTime").toString());
        schedule.setEndTime(payload.get("endTime").toString());
        schedule.setIsAvailable(true);

        return scheduleRepository.save(schedule);
    }

    @GetMapping("/{caregiverId}")
    public List<Schedule> getSchedules(@PathVariable Long caregiverId) {
        return scheduleRepository.findByCaregiverId(caregiverId);
    }

    @DeleteMapping("/{scheduleId}")
    public void deleteSchedule(@PathVariable Long scheduleId) {
        scheduleRepository.deleteById(scheduleId);
    }
}